name: Build and deploy Jekyll 4.x site to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow permissions to write to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Use a stable Ruby version that's well-tested with GitHub Actions
          bundler: '2.4.10'    # Specify a bundler version explicitly
          bundler-cache: false # Disable bundler caching initially


      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Build the site
        run: |
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site       # Jekyll's default output directory
          publish_branch: gh-pages   # Branch to deploy to
          full_commit_message: ${{ github.event.head_commit.message }}
          force_orphan: true         # Make the gh-pages branch a single commit with only the built files